In [4]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [5]:
import numpy as np
import pandas as pd
import warnings
warnings.filterwarnings('ignore')

In [6]:
heart_df = pd.read_csv('/content/drive/MyDrive/heart.csv')
heart_df.head()

,Age,Sex,ChestPainType,RestingBP,Cholesterol,FastingBS,RestingECG,MaxHR,ExerciseAngina,Oldpeak,ST_Slope,HeartDisease
0,40,M,ATA,140,289,0,Normal,172,N,0.0,Up,0
1,49,F,NAP,160,180,0,Normal,156,N,1.0,Flat,1
2,37,M,ATA,130,283,0,ST,98,N,0.0,Up,0
3,48,F,ASY,138,214,0,Normal,108,Y,1.5,Flat,1
4,54,M,NAP,150,195,0,Normal,122,N,0.0,Up,0

In [7]:
heart_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 918 entries, 0 to 917
Data columns (total 12 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Age             918 non-null    int64
 1   Sex             918 non-null    object
 2   ChestPainType   918 non-null    object
 3   RestingBP       918 non-null    int64
 4   Cholesterol     918 non-null    int64
 5   FastingBS       918 non-null    int64
 6   RestingECG      918 non-null    object
 7   MaxHR           918 non-null    int64
 8   ExerciseAngina  918 non-null    object
 9   Oldpeak         918 non-null    float64
 10  ST_Slope        918 non-null    object
 11  HeartDisease    918 non-null    int64
dtypes: float64(1), int64(6), object(5)
memory usage: 86.2+ KB

In [8]:
heart_df.describe()

,Age,RestingBP,Cholesterol,FastingBS,MaxHR,Oldpeak,HeartDisease
count,918.000000,918.000000,918.000000,918.000000,918.000000,918.000000,918.000000
mean,53.510893,132.396514,198.799564,0.233115,136.809368,0.887364,0.553377
std,9.432617,18.514154,109.384145,0.423046,25.460334,1.066570,0.497414
min,28.000000,0.000000,0.000000,0.000000,60.000000,-2.600000,0.000000
25%,47.000000,120.000000,173.250000,0.000000,120.000000,0.000000,0.000000
50%,54.000000,130.000000,223.000000,0.000000,138.000000,0.600000,1.000000
75%,60.000000,140.000000,267.000000,0.000000,156.000000,1.500000,1.000000
max,77.000000,200.000000,603.000000,1.000000,202.000000,6.200000,1.000000

In [9]:
heart_df.describe(include="all")

,Age,Sex,ChestPainType,RestingBP,Cholesterol,FastingBS,RestingECG,MaxHR,ExerciseAngina,Oldpeak,ST_Slope,HeartDisease
count,918.000000,918,918,918.000000,918.000000,918.000000,918,918.000000,918,918.000000,918,918.000000
unique,NaN,2,4,NaN,NaN,NaN,3,NaN,2,NaN,3,NaN
top,NaN,M,ASY,NaN,NaN,NaN,Normal,NaN,N,NaN,Flat,NaN
freq,NaN,725,496,NaN,NaN,NaN,552,NaN,547,NaN,460,NaN
mean,53.510893,NaN,NaN,132.396514,198.799564,0.233115,NaN,136.809368,NaN,0.887364,NaN,0.553377
std,9.432617,NaN,NaN,18.514154,109.384145,0.423046,NaN,25.460334,NaN,1.066570,NaN,0.497414
min,28.000000,NaN,NaN,0.000000,0.000000,0.000000,NaN,60.000000,NaN,-2.600000,NaN,0.000000
25%,47.000000,NaN,NaN,120.000000,173.250000,0.000000,NaN,120.000000,NaN,0.000000,NaN,0.000000
50%,54.000000,NaN,NaN,130.000000,223.000000,0.000000,NaN,138.000000,NaN,0.600000,NaN,1.000000
75%,60.000000,NaN,NaN,140.000000,267.000000,0.000000,NaN,156.000000,NaN,1.500000,NaN,1.000000
max,77.000000,NaN,NaN,200.000000,603.000000,1.000000,NaN,202.000000,NaN,6.200000,NaN,1.000000

Data Preprocessing

In [10]:
#check null values
heart_df.isnull().sum()

Age               0
Sex               0
ChestPainType     0
RestingBP         0
Cholesterol       0
FastingBS         0
RestingECG        0
MaxHR             0
ExerciseAngina    0
Oldpeak           0
ST_Slope          0
HeartDisease      0
dtype: int64

In [11]:
#check duplicates
heart_df.duplicated().sum()

np.int64(0)

In [12]:
#check unique
heart_df.nunique()

Age                50
Sex                 2
ChestPainType       4
RestingBP          67
Cholesterol       222
FastingBS           2
RestingECG          3
MaxHR             119
ExerciseAngina      2
Oldpeak            53
ST_Slope            3
HeartDisease        2
dtype: int64

In [13]:
#extract categorical columns
cat_col = heart_df.select_dtypes(include=['object']).columns

In [14]:
#converting categorical values to numeric values

1. sex: m=0 , f=1
2. chest pain type: ata=0,nap=1,asy=2,ta=3
3. resting ecg: normal=0,st=1,lvh=2
4. exercise angina: n=0,y=1
5. st_slope: up=0, flat=1, down=2

In [15]:
for col in cat_col:
  print(col)
  print((heart_df[col].unique()),list(range(heart_df[col].nunique())))
  heart_df[col].replace((heart_df[col].unique()),range(heart_df[col].nunique()),inplace=True)
  print('*'*90)
  print()

Sex
['M' 'F'] [0, 1]
******************************************************************************************

ChestPainType
['ATA' 'NAP' 'ASY' 'TA'] [0, 1, 2, 3]
******************************************************************************************

RestingECG
['Normal' 'ST' 'LVH'] [0, 1, 2]
******************************************************************************************

ExerciseAngina
['N' 'Y'] [0, 1]
******************************************************************************************

ST_Slope
['Up' 'Flat' 'Down'] [0, 1, 2]
******************************************************************************************

In [16]:
heart_df

,Age,Sex,ChestPainType,RestingBP,Cholesterol,FastingBS,RestingECG,MaxHR,ExerciseAngina,Oldpeak,ST_Slope,HeartDisease
0,40,0,0,140,289,0,0,172,0,0.0,0,0
1,49,1,1,160,180,0,0,156,0,1.0,1,1
2,37,0,0,130,283,0,1,98,0,0.0,0,0
3,48,1,2,138,214,0,0,108,1,1.5,1,1
4,54,0,1,150,195,0,0,122,0,0.0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...
913,45,0,3,110,264,0,0,132,0,1.2,1,1
914,68,0,2,144,193,1,0,141,0,3.4,1,1
915,57,0,2,130,131,0,0,115,1,1.2,1,1
916,57,1,0,130,236,0,2,174,0,0.0,1,1
917,38,0,1,138,175,0,0,173,0,0.0,0,0

In [17]:
heart_df['Cholesterol'].value_counts()

Cholesterol
0      172
254     11
220     10
223     10
204      9
      ...
353      1
278      1
157      1
176      1
131      1
Name: count, Length: 222, dtype: int64

KNN imputer technique to replace 0s

In [18]:
heart_df['Cholesterol'].replace(0,np.nan,inplace=True)

In [19]:
from sklearn.impute import KNNImputer
imputer = KNNImputer(n_neighbors=3)
after_impute = imputer.fit_transform(heart_df)
heart_df = pd.DataFrame(after_impute, columns=heart_df.columns)
heart_df.head()

,Age,Sex,ChestPainType,RestingBP,Cholesterol,FastingBS,RestingECG,MaxHR,ExerciseAngina,Oldpeak,ST_Slope,HeartDisease
0,40.0,0.0,0.0,140.0,289.0,0.0,0.0,172.0,0.0,0.0,0.0,0.0
1,49.0,1.0,1.0,160.0,180.0,0.0,0.0,156.0,0.0,1.0,1.0,1.0
2,37.0,0.0,0.0,130.0,283.0,0.0,1.0,98.0,0.0,0.0,0.0,0.0
3,48.0,1.0,2.0,138.0,214.0,0.0,0.0,108.0,1.0,1.5,1.0,1.0
4,54.0,0.0,1.0,150.0,195.0,0.0,0.0,122.0,0.0,0.0,0.0,0.0

In [20]:
count = 0
for i in heart_df['Cholesterol']:
  if i==0:
    count+=1
print(count)

0

In [21]:
heart_df['RestingBP'][heart_df['RestingBP']==0]

449    0.0
Name: RestingBP, dtype: float64

In [22]:
from sklearn.impute import KNNImputer
heart_df['RestingBP'].replace(0,np.nan,inplace=True)
imputer = KNNImputer(n_neighbors=3)
after_impute = imputer.fit_transform(heart_df)
heart_df = pd.DataFrame(after_impute, columns=heart_df.columns)
heart_df.head()

,Age,Sex,ChestPainType,RestingBP,Cholesterol,FastingBS,RestingECG,MaxHR,ExerciseAngina,Oldpeak,ST_Slope,HeartDisease
0,40.0,0.0,0.0,140.0,289.0,0.0,0.0,172.0,0.0,0.0,0.0,0.0
1,49.0,1.0,1.0,160.0,180.0,0.0,0.0,156.0,0.0,1.0,1.0,1.0
2,37.0,0.0,0.0,130.0,283.0,0.0,1.0,98.0,0.0,0.0,0.0,0.0
3,48.0,1.0,2.0,138.0,214.0,0.0,0.0,108.0,1.0,1.5,1.0,1.0
4,54.0,0.0,1.0,150.0,195.0,0.0,0.0,122.0,0.0,0.0,0.0,0.0

Change columns type to int

In [23]:
withoutOldPeak = heart_df.columns
withoutOldPeak = withoutOldPeak.drop('Oldpeak')
heart_df[withoutOldPeak] = heart_df[withoutOldPeak].astype('int32')

In [24]:
heart_df.sample()

,Age,Sex,ChestPainType,RestingBP,Cholesterol,FastingBS,RestingECG,MaxHR,ExerciseAngina,Oldpeak,ST_Slope,HeartDisease
59,52,0,2,112,342,0,1,96,1,1.0,1,1

In [25]:
heart_df.corr()

,Age,Sex,ChestPainType,RestingBP,Cholesterol,FastingBS,RestingECG,MaxHR,ExerciseAngina,Oldpeak,ST_Slope,HeartDisease
Age,1.000000,-0.055750,0.214164,0.263128,0.057108,0.198039,0.213152,-0.382045,0.215793,0.258612,0.268264,0.282039
Sex,-0.055750,1.000000,-0.179766,-0.009658,0.080395,-0.120076,0.018343,0.189186,-0.190664,-0.105734,-0.150693,-0.305445
ChestPainType,0.214164,-0.179766,1.000000,0.073016,0.038855,0.155111,0.112067,-0.273076,0.324049,0.300846,0.352364,0.459017
RestingBP,0.263128,-0.009658,0.073016,1.000000,0.113194,0.067556,0.094144,-0.109329,0.152621,0.174464,0.082401,0.118333
Cholesterol,0.057108,0.080395,0.038855,0.113194,1.000000,0.058798,0.074925,-0.028855,0.083761,0.065988,0.071345,0.101263
FastingBS,0.198039,-0.120076,0.155111,0.067556,0.058798,1.000000,0.050707,-0.131438,0.060451,0.052698,0.175774,0.267291
RestingECG,0.213152,0.018343,0.112067,0.094144,0.074925,0.050707,1.000000,0.048552,0.036119,0.114428,0.078807,0.061011
MaxHR,-0.382045,0.189186,-0.273076,-0.109329,-0.028855,-0.131438,0.048552,1.000000,-0.370425,-0.160691,-0.343419,-0.400421
ExerciseAngina,0.215793,-0.190664,0.324049,0.152621,0.083761,0.060451,0.036119,-0.370425,1.000000,0.408752,0.428706,0.494282
Oldpeak,0.258612,-0.105734,0.300846,0.174464,0.065988,0.052698,0.114428,-0.160691,0.408752,1.000000,0.501921,0.403951
ST_Slope,0.268264,-0.150693,0.352364,0.082401,0.071345,0.175774,0.078807,-0.343419,0.428706,0.501921,1.000000,0.558771
HeartDisease,0.282039,-0.305445,0.459017,0.118333,0.101263,0.267291,0.061011,-0.400421,0.494282,0.403951,0.558771,1.000000

Data visualization

In [26]:
!pip install plotly

Requirement already satisfied: plotly in /usr/local/lib/python3.12/dist-packages (5.24.1)
Requirement already satisfied: tenacity>=6.2.0 in /usr/local/lib/python3.12/dist-packages (from plotly) (9.1.4)
Requirement already satisfied: packaging in /usr/local/lib/python3.12/dist-packages (from plotly) (26.2)

In [27]:
import plotly.express as px

In [28]:
px.line(heart_df.corr()['HeartDisease'][:-1].sort_values())

Age and Heart Disease Distribution

In [29]:
px.sunburst(heart_df,path=['HeartDisease','Age'])

In [30]:
px.histogram(heart_df,x='Age',color='HeartDisease')

Percentage of Heart Disease data Distribution

In [31]:
px.pie(heart_df,names='HeartDisease',title='Percentage of heart disease classes distrribution')

Sex vs Heart Disease

In [32]:
px.histogram(heart_df,x='Sex',color='HeartDisease')

Chest Pain type vs Heart Disease

In [33]:
px.histogram(heart_df,x='ChestPainType',color='HeartDisease')

RestingBP vs Heart Disease

In [34]:
px.sunburst(heart_df,path=['HeartDisease','RestingBP'])

FastingBS vs Heart Disease

In [35]:
px.histogram(heart_df,x='FastingBS',color='HeartDisease')

MaxHR vs Heart Disease

In [36]:
px.sunburst(heart_df,path=['HeartDisease','MaxHR'])

In [37]:
px.violin(heart_df,x='HeartDisease',y='MaxHR')

Oldpeak vs Heart Disease

In [38]:
px.violin(heart_df,x='HeartDisease',y='Oldpeak')

St_slope vs Heart Disease

In [39]:
px.histogram(heart_df,x='ST_Slope',color='HeartDisease')

Exercise Angina vs Heart disease

In [40]:
px.histogram(heart_df,x='ExerciseAngina',color='HeartDisease')

TRAIN TEST SPLIT

In [42]:
from sklearn.model_selection import train_test_split

x_train,x_test,y_train,y_test = train_test_split(
    heart_df.drop('HeartDisease',axis=1),
    heart_df['HeartDisease'],
    test_size=0.2,
    random_state=42,
    stratify=heart_df['HeartDisease']
)

Model Training

Logistic Regression

In [46]:
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score

solver = ['lbfgs', 'liblinear', 'newton-cg', 'newton-cholesky', 'sag', 'saga']
best_solver = ''
test_score = np.zeros(6)
for i,n in enumerate(solver):
  lr = LogisticRegression(solver=n).fit(x_train,y_train)
  test_score[i] = lr.score(x_test,y_test)
  if test_score[i] == test_score.max():
    best_solver = n

print(best_solver)
lr = LogisticRegression(solver=best_solver)
lr.fit(x_train,y_train)
lr_pred = lr.predict(x_test)
print(f'LogisticRegression Score: {accuracy_score(y_test,lr_pred)}')

newton-cholesky
LogisticRegression Score: 0.8586956521739131

In [58]:
import pickle
file = open('LogisticR.pkl','wb')
pickle.dump(lr,file)

SVM

In [47]:
from sklearn.svm import SVC
from sklearn.metrics import f1_score

kernels = {'linear':0, 'poly':0, 'rbf':0, 'sigmoid':0}
best = ''
for i in kernels:
  svm = SVC(kernel=i)
  svm.fit(x_train,y_train)
  yhat = svm.predict(x_test)
  kernels[i] = f1_score(y_test,yhat,average='weighted')
  if kernels[i] == max(kernels.values()):
    best = i
print(best)
svm = SVC(kernel=best)
svm.fit(x_train,y_train)
svm_pred = svm.predict(x_test)
print(f'SVM f1_score kernel({best}): {f1_score(y_test,svm_pred, average="weighted")}')

linear
SVM f1_score kernel(linear): 0.8422922535440344

In [60]:
import pickle
file = open('SVM.pkl','wb')
pickle.dump(svm,file)

Decision Tree

In [50]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import GridSearchCV

dt = DecisionTreeClassifier(class_weight='balanced')
param_grid = {
    'max_depth' : [3,4,5,6,7,8],
    'min_samples_split' : [2,3,4],
    'min_samples_leaf' : [1,2,3,4],
    'random_state' : [0,42]
}
grid_search = GridSearchCV(dt,param_grid,cv=5)
grid_search.fit(x_train,y_train)

Ctree = DecisionTreeClassifier(**grid_search.best_params_,  class_weight='balanced')
Ctree.fit(x_train,y_train)
dtc_pred = Ctree.predict(x_test)
print(f'DecisionTreeClassifier Score: {accuracy_score(y_test,dtc_pred)}')

DecisionTreeClassifier Score: 0.8097826086956522

In [61]:
import pickle
file = open('DT.pkl','wb')
pickle.dump(Ctree,file)

Random Forest

In [54]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import GridSearchCV

rfc = RandomForestClassifier()
param_grid = {
    'n_estimators' : [100,200],
    'max_features' : ['sqrt', 'log2'],
    'max_depth' : [None,10,20]
}
grid_search = GridSearchCV(rfc,param_grid)
grid_search.fit(x_train,y_train)
rfctree = RandomForestClassifier(**grid_search.best_params_)
rfctree.fit(x_train,y_train)
rfc_pred = rfctree.predict(x_test)
print(f'RandomForestClassifier Score: {accuracy_score(y_test,rfc_pred)}')

RandomForestClassifier Score: 0.875

In [62]:
import pickle
file = open('RF.pkl','wb')
pickle.dump(rfctree,file)